---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    type: local
spec:
  volumeMode: Filesystem
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mysql
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
      - name: pv-storage
        persistentVolumeClaim:
          claimName: pvc-mysql
      containers:
      - image: mysql:5.6
        name: mysql
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: app
        - name: MYSQL_USER
          value: appuser
        - name: MYSQL_PASSWORD
          value: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - mountPath: "/var/lib/mysql"
          name: pv-storage


---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app
    spec:
      containers:
      - image: cevahirb/app:latest
        name: cevahirb
        resources: {}
        env:
          # Use secret in real usage
        - name: MYSQL_USERNAME
          value: "appuser"
        - name: MYSQL_PASSWORD
          value: "password"
        - name: MYSQL_INSTANCE_NAME
          value: "app"
        - name: MYSQL_PORT_3306_TCP_ADDR
          value: "mysql"
        - name: MYSQL_PORT_3306_TCP_PORT
          value: "3306"
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: app
  name: app
spec:
  ports:
  - nodePort: 32700
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: app
  type: NodePort
status:
  loadBalancer: {}

