---
- hosts: Master
  become: true
  tasks:

  - name: Ensure running application
  k8s_facts:
    namespace: sample
    kind: Pod
    label_selectors:
  - name: Jenkins Sa
    command: kubectl create ns jenkins
  - name: Jenkins Sa
    command: kubectl create serviceaccount jenkins
  - name: Jenkins ClusterRoleBinding
    shell:
      cmd: |
        cat <<EOF | jenkins-clusterrolebinding.yaml << EOF
          ---
          apiVersion: rbac.authorization.k8s.io/v1
          kind: ClusterRoleBinding
          metadata:
            name: jenkins-rolebinnding
          roleRef:
            apiGroup: rbac.authorization.k8s.io
            kind: ClusterRole
            name: cluster-admin
          subjects:
          - kind: ServiceAccount
            name: jenkins
            namespace: jenkins
          EOF
        kubectl apply -f jenkins-clusterrolebinding.yaml -n jenkins
  - name: Get Token Sa
    command: kubectl get secret $(kubectl get sa jenkins -n jenkins -o jsonpath={.secrets[0].name}) -n jenkins -o jsonpath={.data.token} | base64 --decode
    register: jenkins_token

  - name: Copy jenkins_token to local file
    local_action: copy content="{{ jenkins_token.stdout_lines[0] }}" dest="{{ playbook_dir }}/jenkins_token"
    become: false